DECLARE SENTCONST E F G H;
MARK init2;
DECLARE INDVAR a b c d e f g;
FETCH fetch3.tst FROM init3  TO end3 ;
DECLARE PREDCONST P1 1;
DECLARE PREDCONST Q1 1;
DECLARE PREDCONST P3 2;
LOAD fetch.lsp;
MARK end2;
DECLARE PREDCONST Q3 2;

