; * This file verifies the operations of input output.
; * It must be run on the HGKM interpreter.

(SETQ OS (HGKM-OSOPEN "/tmp/sym"))
(SETQ SEXPLIST '(A B C (A B) C D))
(MAPCAR '(LAMBDA (x) (PROGN (CHAN-PRINC x OS) (CHAN-CRLF OS))) SEXPLIST)
(HGKM-CLOSE OS)
(SETQ IS (HGKM-ISOPEN "/tmp/sym"))
(DEFUN SYM-TST (SLIST)
 (IF (NULL SLIST) T
  (LET ((SEXP (CHAN-READ IS)))
   (IF (EQUAL SEXP (CAR SLIST))
    (SYM-TST (CDR SLIST)) NIL))))
(SETQ RES1 (SYM-TST SEXPLIST))
(HGKM-CLOSE IS)
 
(SETQ OS (HGKM-OSOPEN "/tmp/sym"))
(SELECT OS)
(MAPCAR '(LAMBDA (x) (PROGN (HGKM-PRINC x) (CRLF))) SEXPLIST)
(HGKM-CLOSE OS)
(SETQ IS (HGKM-ISOPEN "/tmp/sym"))
(SELECT IS)
(DEFUN SYM-TST (SLIST)
 (IF (NULL SLIST) T
  (LET ((SEXP (HGKM-READ)))
   (IF (EQUAL SEXP (CAR SLIST))
    (SYM-TST (CDR SLIST)) NIL))))
(SETQ RES2 (SYM-TST SEXPLIST))
(HGKM-CLOSE IS)


(SETQ CHARLIST '(123 122 121 45 65 74 34 123))
(SETQ OC (HGKM-OCOPEN "/tmp/chr"))
(MAPCAR '(LAMBDA (x) (CHAN-CHO x OC)) CHARLIST)
(HGKM-CLOSE OC)
(SETQ IC (HGKM-ICOPEN "/tmp/chr"))
(DEFUN CHR-TST (CLIST)
 (IF (NULL CLIST) T
  (LET ((SEXP (CHAN-CHI IC)))
   (IF (EQUAL SEXP (CAR CLIST))
    (CHR-TST (CDR CLIST)) NIL))))
(SETQ RES3 (CHR-TST CHARLIST))
(HGKM-CLOSE IC)
 
(SETQ OC (HGKM-OCOPEN "/tmp/chr"))
(SELECT OC)
(MAPCAR '(LAMBDA (x) (HGKM-CHO x)) CHARLIST)
(HGKM-CLOSE OC)
(SETQ IC (HGKM-ICOPEN "/tmp/chr"))
(SELECT IC)
(DEFUN CHR-TST (CLIST)
 (IF (NULL CLIST) T
  (LET ((SEXP (HGKM-CHI)))
   (IF (EQUAL SEXP (CAR CLIST))
    (CHR-TST (CDR CLIST)) NIL))))
(SETQ RES4 (CHR-TST CHARLIST))
(HGKM-CLOSE IC)


(IF (AND RES1 RES2 RES3 RES4) 
 (FORMAT T "~% THE TEST WORKED ~%~%")
 (FORMAT T "~% THE TEST DID NON SUCCEED ~%~%"))
 

